name: publish_develop_dms_module
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip DMS Folder
      run: |
        cd module/dms
        ls -alrt
    - uses: zoexx/github-action-json-file-properties@release
      with:
        file_path: "module/dms/metadata.json"
    - name: Get Metadata Json Properties
      id: json_properties
      run: |
        pwd
        echo ${{steps.json_properties.outputs.name}}
        echo ${{steps.json_properties.outputs.version}}
        zip -r dms.zip . 
        ls -alrt

