name: publish_develop_dms_module
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Module
      run: |
        cd module/dms
        ls -alrt
    - name: Zip Module
      id: json_properties
      uses: ActionsTools/read-json-action@main
      with:
          file_path: "module/dms/metadata.json"
    - run: |
        pwd
        cd module/dms
        echo ${{steps.json_properties.outputs.name}}
        echo ${{steps.json_properties.outputs.version}}
        zip -r dms-${{steps.json_properties.outputs.version}}.zip . 
        ls -alrt

