name: publish_develop_dms_module
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip DMS Folder
      run: |
        cd module/dms
        ls -alrt
        echo 'METADATA_JSON<<EOF' >> $GITHUB_ENV
        cat metadata.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo '${{ fromJson(env.METADATA_JSON).version }}'
        zip -r dms.zip . 
        ls -alrt
    - name: Publish ZIP to S3
      run: echo "Release"
